/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
    BNavText: typeof import('bootstrap-vue-next/components/BNav')['BNavText']
    BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
    BPlaceholderTable: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderTable']
    IBiTranslate: typeof import('~icons/bi/translate')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
  }
}

// For TSX support
declare global {
  const BAvatar: typeof import('bootstrap-vue-next/components/BAvatar')['BAvatar']
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
  const BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
  const BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
  const BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
  const BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
  const BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
  const BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
  const BNavItemDropdown: typeof import('bootstrap-vue-next/components/BNav')['BNavItemDropdown']
  const BNavText: typeof import('bootstrap-vue-next/components/BNav')['BNavText']
  const BPlaceholder: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholder']
  const BPlaceholderTable: typeof import('bootstrap-vue-next/components/BPlaceholder')['BPlaceholderTable']
  const IBiTranslate: typeof import('~icons/bi/translate')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}